[workspace]
members = ["tlvc", "tool", "text"]
resolver = "3"

[workspace.dependencies]
clap            = { version = "4", features = ["derive"] }
crc             = { version = "3.4" }
ron             = { version = "0.8" }
serde           = { version = "1", features = ["derive"] }
zerocopy        = { version = "0.8" }
zerocopy-derive = { version = "0.8" }
