[package]
name = "tlvc"
version = "0.4.1"
edition = "2024"

[dependencies]
crc.workspace               = true
thiserror.workspace         = true
zerocopy.workspace          = true
zerocopy-derive.workspace   = true

[dev-dependencies]
tlvc-text.path      = "../text"

[features]
default = []
alloc = []
