[package]
name = "tlvc-text"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
ron = "0.8"
tlvc = {path = "../tlvc"}
zerocopy = "0.6"
